### ISSUE TITLE
HD Wallet API Should Use "Derive" Address Instead of "Generate"

### ISSUE THREAD

**Issue by acityinohio** [blockcypher/php-client#17]
Hi @josecelano, any chance you could take a look at the HD Wallet address derivation endpoint? Specifically this method:

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Api/HDWallet.php#L175

A customer provided us some feedback that this line should be using "derive" instead of "generate":

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Api/HDWallet.php#L188

Didn't want to modify it myself as I'm not sure how it may change other parts of the PHP SDK, but maybe that could be changed and the method name should be "deriveAddress" instead of "generateAddress." Thanks!

**Comment by josecelano** [comment]
Hi @acityinohio I will take a look, I have some minor bug fixes pending to do but I have been very busy.

**Comment by josecelano** [comment]
Hey @acityinohio I am working on the change but there are more changes:

* HDWalletGenerateAddressResponse has been removed.
* HDChain and HDAddress have been added.

I think I will finish tomorrow and I will relase v1.3.1

**Comment by acityinohio** [comment]
Thanks so much @josecelano! Very much appreciated.

**Comment by josecelano** [comment]
Fixed with commit e03ca1b3b7ccb2398a88bbfeb67d1ff803ede178.

Anyway now they should not use HDWallet, they should use HDWalletClient. In fact, I have not added the method in HDWallet, it¡s in HDWalletClient::deriveAddress

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Client/HDWalletClient.php#L251

Since previous versions I have been moving static methods from API resources (`lib/BlockCypher/Api`) to clients (`lib/BlockCypher/Client`). I want to remove those methods in a future major version release.
