### ISSUE TITLE
Uncompressed public keys not working?

### ISSUE THREAD

**Issue by AugustoResende** [blockcypher/php-client#27]
Really is not possible make transactions using uncompressed public keys? I REALLY need this or i will need abandon blockcypher apis...

**Comment by matthieu** [comment]
"Because they’re easy to use, and because they reduce almost by half the block chain space used to store public keys for every spent output, compressed public keys are the default in Bitcoin Core and are the recommended default for all Bitcoin software."
- https://bitcoin.org/en/developer-guide#public-key-formats
