### ISSUE TITLE
Invalid option 'callback_url' at payment forward client

### ISSUE THREAD

**Issue by LSDx** [blockcypher/php-client#6]
Hello. I can't figure out what is wrong. I'm trying to create new payment forward address but it throws an exception that theres is invalid option 'callback_url'.
So here's the exception itesef : http://prntscr.com/9qkzpr
And the code : http://prntscr.com/9qkydo

**Comment by josecelano** [comment]
Hi @LSDx this bug is the same as #3 .I have fixed it with latest commits but I have not released a new version yet, I will do it asap. In the mean time you have to options:

1.- Patch your version:

You have to chage this llines:

https://github.com/blockcypher/php-client/blob/master/lib/BlockCypher/Validation/ModelAccessorValidator.php#L27-L33

2.- Change your API context options array to:

```
    $config = array(
        'mode' => 'sandbox',
        'log.LogEnabled' => true,
        'log.FileName' => __DIR__ . '/BlockCypher.log',
        'log.LogLevel' => 'DEBUG',
        'validation.level' => 'log',
    );
```
You have to add explicit `validation.level` option to your settings to avoid this bug.

In case you are also using a `sdk_config.ini` file you have to add these lines:

```
[validation]
validation.level = log
```

Let me know if that fixs your problem.

**Comment by LSDx** [comment]
What is the sandbox mode? Is it necessary?

**Comment by josecelano** [comment]
Sorry @LSDx I copied/pasted from https://github.com/blockcypher/php-client/blob/master/sample/bootstrap.php

Really option `mode => sandbox' is not used for the time being. Both sandbox and live mode point to the same API endpoints. You can use Bitcoin Tesnet or better BlockCYpher Testnet if you do not want to use real bitcoins. The sandbox mode was added in the client only in case the BlockCypher API also enable a sandbox mode in the future. For example for creating fake webhooks or payment forwardings, and so on.

P.S.: I recommend this blog post about testing you app: https://medium.com/blockcypher-blog/testnet-is-not-for-testing-5afa78b1394#.519vaav8s

**Comment by josecelano** [comment]
hi @LSDx is your problem fixed? Can I close this issue? I will release a new version with default validation level to `log`.

**Comment by LSDx** [comment]
Hi, @josecelano . 
Yes, the problem is gone! Thank you!

**Comment by josecelano** [comment]
With this new release: https://github.com/blockcypher/php-client/releases/tag/v1.3.0
default validation level is set to `log` if it is not defined in config.
